### ISSUE TITLE
-o yaml outputs json

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#1160]
* `-o yaml`: prints json
* `-o json`: prints json
* no `-o` flag: prints yaml

```sh
$ ./akash query account akash1gumjaae66pnk4jvea6v6k8s02w3au3986zkvke -o yaml
{"@type":"/cosmos.auth.v1beta1.BaseAccount","address":"akash1gumjaae66pnk4jvea6v6k8s02w3au3986zkvke","pub_key":null,"account_number":"6895","sequence":"0"}
$ ./akash query account akash1gumjaae66pnk4jvea6v6k8s02w3au3986zkvke -o json
{"@type":"/cosmos.auth.v1beta1.BaseAccount","address":"akash1gumjaae66pnk4jvea6v6k8s02w3au3986zkvke","pub_key":null,"account_number":"6895","sequence":"0"}
$ ./akash query account akash1gumjaae66pnk4jvea6v6k8s02w3au3986zkvke
'@type': /cosmos.auth.v1beta1.BaseAccount
account_number: "6895"
address: akash1gumjaae66pnk4jvea6v6k8s02w3au3986zkvke
pub_key: null
sequence: "0"
```

**Comment by hydrogen18** [comment]
Weirdly, `-o text` writes JSON. Reviewing the cosmos SDK code this appears to be intentional

```
$ ../../akash --home=$PWD/cache query account akash1dc2wnk9alyxumdhsun8l0w8jlma253dhkfsk78 -o text
'@type': /cosmos.auth.v1beta1.BaseAccount
account_number: "0"
address: akash1dc2wnk9alyxumdhsun8l0w8jlma253dhkfsk78
pub_key: null
sequence: "0"
```

**Comment by troian** [comment]
another issue `-o` does not work for some commands

**Comment by boz** [comment]
I _think_ this might have been fixed.  Verify?

**Comment by troian** [comment]
still an issue on `v0.12.2-rc0` `-o text` outputs `yaml`. will have to contact cosmos team
