### ISSUE TITLE
Lease events have wrong time stamp

### ISSUE THREAD

**Issue by coffeeroaster** [ovrclk/akash#1334]
Provider: `akash1f6gmtjpx4r8qda9nxjwq26fp5mcjyqmaq5m6j7`

Lease event of type `"reason": "Scheduled"` has a correct timestamp:
```
{
  "type": "Normal",
  "reportingController": "default-scheduler",
  "reportingInstance": "default-scheduler-mainnet-ewr1-provider-master",
  "time": "2021-07-26T18:21:05.891718Z",
  "reason": "Scheduled",
...
}
```

However, every other Lease event has an incorrect time stamp. Example:

```
{
  "type": "Normal",
  "time": "0001-01-01T00:00:00Z",
  "reason": "SuccessfulCreate",
  "note": "Created pod: web-75979bd7df-rqvm5",
  "object": {
    "kind": "ReplicaSet",
    "namespace": "5hi5um9qfk7ve4lce1dech3qne9qlna38bhgr93thbqae",
    "name": "web-75979bd7df"
  }
}
```

**Comment by dmikey** [comment]
@coffeeroaster can you give us a bit more detail in the ticket, incase we are unable to pull logs before we get to this.

**Comment by coffeeroaster** [comment]
Fixed.

**Comment by hydrogen18** [comment]
Based on the time displayed, we're substituting a 0 value for a unix time stamp and then creating the one you see there. Thanks for reporting this.

**Comment by hydrogen18** [comment]
I was able to reproduce this pretty quickly & it is still an issue.

```
{
  "type": "Normal",
  "time": "0001-01-01T00:00:00Z",
  "reason": "Started",
  "note": "Started container redis",
  "object": {
    "kind": "Pod",
    "namespace": "39pfap27vjj338nv5db0rqk2uvqscih0vss9i0q3op9b2",
    "name": "redis-6df85cfc55-rlcpx"
  },
  "lease_id": {
    "owner": "akash1zmjsezgj3ul8dqunx8dhah38t9tr2gn2cf5pqj",
    "dseq": 1211,
    "gseq": 1,
    "oseq": 1,
    "provider": "akash1gx4aevud37w4d6kfd5szgp87lmkqvumaz57yww"
  }
}

```

I'll track this down and figure out where we need to be adding a timestamp

**Comment by boz** [comment]
Is this on `mainnet` @hydrogen18?

**Comment by hydrogen18** [comment]
No it's on my testnet which is ahead of mainnet

**Comment by hydrogen18** [comment]
The `.EventTime` field from the kube API is always 0.

I just rant `kubectl get events --watch -A --output=json` in a terminal and I don't event think event time is a real thing that comes from kubernetes? It shows stuff like this

```
{
    "apiVersion": "v1",
    "count": 1,
    "eventTime": null,
    "firstTimestamp": "2021-09-14T19:54:06Z",
    "involvedObject": {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "name": "web",
        "namespace": "6hvm3538ll2b52unpvsb6lear1psftb60drs7uj520h5g",
        "resourceVersion": "2573",
        "uid": "3977d7b3-116e-4e63-8e1a-7b2e44558073"
    },
    "kind": "Event",
    "lastTimestamp": "2021-09-14T19:54:06Z",
    "message": "Scaled up replica set web-5b59b959d6 to 1",
    "metadata": {
        "creationTimestamp": "2021-09-14T19:54:06Z",
        "name": "web.16a4c8584c9f0da7",
        "namespace": "6hvm3538ll2b52unpvsb6lear1psftb60drs7uj520h5g",
        "resourceVersion": "2802",
        "uid": "bbeac50b-cf0f-4018-9c65-e8d53994188e"
    },
    "reason": "ScalingReplicaSet",
    "reportingComponent": "",
    "reportingInstance": "",
    "source": {
        "component": "deployment-controller"
    },
    "type": "Normal"
}
```

The CreationTimestamp is literally when the resource was created, so it isn't accurate for the event. Maybe we just fill it in on provider side with `time.Now()` and call it done?

It looks like `eventTime` being null is an expected behavior: https://github.com/kubernetes/kubernetes/issues/90482#issuecomment-619440160

**Comment by arijitAD** [comment]
The LeaseEvent struct doesn’t seem to have a time field in master.
Closing this issue
https://github.com/ovrclk/akash/blob/c89507db22a272436f0707360a2c695d832e9cb5/provider/cluster/types/types.go#L153-L160
